// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/scanner/scanner.go

// Package mock_scanner is a generated GoMock package.
package mock_scanner

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/ntsd/backend-engineer-challenge-new/internal/model"
)

// MockScanner is a mock of Scanner interface.
type MockScanner struct {
	ctrl     *gomock.Controller
	recorder *MockScannerMockRecorder
}

// MockScannerMockRecorder is the mock recorder for MockScanner.
type MockScannerMockRecorder struct {
	mock *MockScanner
}

// NewMockScanner creates a new mock instance.
func NewMockScanner(ctrl *gomock.Controller) *MockScanner {
	mock := &MockScanner{ctrl: ctrl}
	mock.recorder = &MockScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScanner) EXPECT() *MockScannerMockRecorder {
	return m.recorder
}

// CreateScan mocks base method.
func (m *MockScanner) CreateScan(repo model.Repository) (*model.Scan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScan", repo)
	ret0, _ := ret[0].(*model.Scan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateScan indicates an expected call of CreateScan.
func (mr *MockScannerMockRecorder) CreateScan(repo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScan", reflect.TypeOf((*MockScanner)(nil).CreateScan), repo)
}
